# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def test_pods
  pod "Nimble"
  pod "RxTest"
  pod "RxBlocking"
end
target 'JipJung' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for JipJung
  pod "SwiftLint"
  pod "RxSwift"
  pod "RxCocoa"
  pod "RxRelay"
  pod "RealmSwift"
  pod "SnapKit"
  pod "Firebase/Storage"
  target 'MaximTests' do
    test_pods
  end
  target 'MeTests' do
    test_pods
  end
  target 'RealmTests' do
    test_pods
  end
end
